version: "3"
services:
  pod_health:
    container_name: pod_health
    image: registry.gitlab.com/panupong.dev.webb/gitops-application-builder:6ae451b
    environment:
      - PORT=3000
    ports:
      - "4600:3000"
    


networks:
  default:
    external:
      name: applications_dev
