version: "3"
services:
  web_server:
    container_name: web_server
    image: nginx:1.20
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4500:80"


networks:
  default:
    external:
      name: applications_dev